### ISSUE TITLE
[Suggestion] Sound issues.

### ISSUE THREAD

**Issue by Qee1y** [YUNG-GANG/YUNGs-Better-End-Island#12] opened 2023-10-27 03:07 UTC
It's strange that when a tower is activated and explodes, but the explosion has no sound and is very quiet, which only makes people feel strange.

**Comment by yungnickyoung** [comment] 2023-11-03 03:22
Are you using a sound mod like Sound Physics Remastered? It could be a mod like that interfering with the sounds.

**Comment by Qee1y** [comment] 2023-11-03 04:06
Yes.  But how to solve this problem, but I don't want to delete this mod

**Comment by yungnickyoung** [comment] 2024-01-24 01:06
Marking this as duplicate of #19

**Closed as completed by yungnickyoung** 2024-01-24 01:06 UTC
Labels: duplicate
