### ISSUE TITLE
incompatibility with Stellarity

### ISSUE THREAD

**Issue by jojofenin99** [YUNG-GANG/YUNGs-Better-End-Island#16] opened 2023-11-22 19:39 UTC
I was playing with this mod and stellarity but stellarity also makes changes to the end island so is the some way to overwrite the generation so that only yung's better island changes the end island and not stellarity. :D Have a good day!!!

**Comment by SiverDX** [comment] 2023-11-22 23:33
probably not since that's a datapack and I think part of it's worldgen is done by commands

and even if you could, disabling parts of it would probably break other parts

**Comment by yungnickyoung** [comment] 2024-01-24 01:10
Marking as duplicate of #14. Will look into it soon

**Closed as completed by yungnickyoung** 2024-01-24 01:10 UTC
Labels: duplicate
